In [2]:
import pandas as pd
import altair as alt

In [3]:
df_episodes = pd.read_csv("../data/kaggle_data/simpsons_episodes.csv")
df_episodes

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0

In [4]:
df_episodes = df_episodes[df_episodes['season'] != 28]
df_episodes

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0

In [5]:
df_ratings = df_episodes[['original_air_year', 'imdb_rating', 'season']]
df_ratings = df_ratings.groupby('season').agg({'imdb_rating': 'mean','original_air_year': 'median'})
df_ratings['original_air_year'] = round(df_ratings['original_air_year']+0.1)
df_ratings

        imdb_rating  original_air_year
season
1          7.807692             1990.0
2          8.040909             1991.0
3          8.154167             1992.0
4          8.268182             1993.0
5          8.336364             1994.0
6          8.312000             1995.0
7          8.324000             1996.0
8          8.220000             1997.0
9          7.844000             1998.0
10         7.569565             1999.0
11         7.290909             2000.0
12         7.361905             2001.0
13         7.140909             2002.0
14         7.077273             2003.0
15         7.045455             2004.0
16         7.042857             2005.0
17         6.863636             2006.0
18         7.000000             2007.0
19         6.935000             2008.0
20         6.895238             2009.0
21         6.821739             2010.0
22         6.804545             2011.0
23         6.813636             2012.0
24         6.777273             2013.0
25         6.831818             2014.0
26         6.704545             2015.0
27         6.786364             2016.0

In [16]:
alt.Chart(df_ratings).mark_line(point=True).encode(
    x=alt.X('original_air_year:O', title='Year'),
    y=alt.Y('imdb_rating:Q', title='Rating')
)

alt.Chart(...)