In [2]:
import pandas as pd
import altair as alt

In [3]:
df_episodes = pd.read_csv("../data/kaggle_data/simpsons_episodes.csv")
df_episodes

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0

In [4]:
df_episodes = df_episodes[df_episodes['season'] != 28]
df_episodes

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0

## fill in missing values
found at https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)

In [5]:
df_episodes[(df_episodes['season']==8) & (df_episodes['number_in_season']==7)]['us_viewers_in_millions'] = 12.2
df_episodes[(df_episodes['season']==8) & (df_episodes['number_in_season']==8)]['us_viewers_in_millions'] = 14.4
df_episodes[(df_episodes['season']==8) & (df_episodes['number_in_season']==20)]['us_viewers_in_millions'] = 13.3
df_episodes

C:\Users\20203666\AppData\Local\Temp\ipykernel_32168\1929254601.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_episodes[(df_episodes['season']==8) & (df_episodes['number_in_season']==7)]['us_viewers_in_millions'] = 12.2
C:\Users\20203666\AppData\Local\Temp\ipykernel_32168\1929254601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_episodes[(df_episodes['season']==8) & (df_episodes['number_in_season']==8)]['us_viewers_in_millions'] = 14.4
C:\Users\20203666\AppData\Local\Temp\ipykernel_32168\1929254601.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_episodes[(df_episodes['season']==8) & (df_episodes['number_in_season']==20)]['us_viewers_in_millions'] = 13.3

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0

In [6]:
season_years = df_episodes.groupby('season')['original_air_year'].agg(['min', 'max'])

season_years['season_label'] = (
        'Season ' + season_years.index.astype(str) +
        ' (' + season_years['min'].astype(str) + ')'
        #'-' + season_years['max'].astype(str) + ')'
)

df_episodes['season_label'] = df_episodes['season'].map(season_years['season_label'])
df_episodes

C:\Users\20203666\AppData\Local\Temp\ipykernel_32168\1480408358.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_episodes['season_label'] = df_episodes['season'].map(season_years['season_label'])

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views,season_label
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0,Season 1 (1989)
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0,Season 1 (1989)
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0,Season 2 (1990)
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0,Season 2 (1990)
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0,Season 2 (1990)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0,Season 23 (2011)
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0,Season 23 (2011)
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0,Season 24 (2012)
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0,Season 25 (2013)
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0,Season 25 (2013)

## Question 1

In [7]:
df_ratings = df_episodes[['original_air_year', 'imdb_rating', 'season']]
df_ratings = df_ratings.groupby('season').agg({'imdb_rating': 'mean','original_air_year': 'median'})
df_ratings['original_air_year'] = round(df_ratings['original_air_year']+0.1)
df_ratings

        imdb_rating  original_air_year
season
1          7.807692             1990.0
2          8.040909             1991.0
3          8.154167             1992.0
4          8.268182             1993.0
5          8.336364             1994.0
6          8.312000             1995.0
7          8.324000             1996.0
8          8.220000             1997.0
9          7.844000             1998.0
10         7.569565             1999.0
11         7.290909             2000.0
12         7.361905             2001.0
13         7.140909             2002.0
14         7.077273             2003.0
15         7.045455             2004.0
16         7.042857             2005.0
17         6.863636             2006.0
18         7.000000             2007.0
19         6.935000             2008.0
20         6.895238             2009.0
21         6.821739             2010.0
22         6.804545             2011.0
23         6.813636             2012.0
24         6.777273             2013.0
25         6.831818             2014.0
26         6.704545             2015.0
27         6.786364             2016.0

In [8]:
alt.Chart(df_ratings).mark_line(point=True).encode(
    x=alt.X('original_air_year:O', title='Year'),
    y=alt.Y('imdb_rating:Q', title='Rating')
)

alt.Chart(...)

In [9]:
df_ratings = df_episodes[['season_label', 'imdb_rating', 'season']]
df_ratings = df_ratings.groupby('season_label').agg({'imdb_rating': 'mean', 'season': 'median'})
df_ratings['season_label'] = df_ratings.index
df_ratings

                  imdb_rating  season      season_label
season_label
Season 1 (1989)      7.807692     1.0   Season 1 (1989)
Season 10 (1998)     7.569565    10.0  Season 10 (1998)
Season 11 (1999)     7.290909    11.0  Season 11 (1999)
Season 12 (2000)     7.361905    12.0  Season 12 (2000)
Season 13 (2001)     7.140909    13.0  Season 13 (2001)
Season 14 (2002)     7.077273    14.0  Season 14 (2002)
Season 15 (2003)     7.045455    15.0  Season 15 (2003)
Season 16 (2004)     7.042857    16.0  Season 16 (2004)
Season 17 (2005)     6.863636    17.0  Season 17 (2005)
Season 18 (2006)     7.000000    18.0  Season 18 (2006)
Season 19 (2007)     6.935000    19.0  Season 19 (2007)
Season 2 (1990)      8.040909     2.0   Season 2 (1990)
Season 20 (2008)     6.895238    20.0  Season 20 (2008)
Season 21 (2009)     6.821739    21.0  Season 21 (2009)
Season 22 (2010)     6.804545    22.0  Season 22 (2010)
Season 23 (2011)     6.813636    23.0  Season 23 (2011)
Season 24 (2012)     6.777273    24.0  Season 24 (2012)
Season 25 (2013)     6.831818    25.0  Season 25 (2013)
Season 26 (2014)     6.704545    26.0  Season 26 (2014)
Season 27 (2015)     6.786364    27.0  Season 27 (2015)
Season 3 (1991)      8.154167     3.0   Season 3 (1991)
Season 4 (1992)      8.268182     4.0   Season 4 (1992)
Season 5 (1993)      8.336364     5.0   Season 5 (1993)
Season 6 (1994)      8.312000     6.0   Season 6 (1994)
Season 7 (1995)      8.324000     7.0   Season 7 (1995)
Season 8 (1996)      8.220000     8.0   Season 8 (1996)
Season 9 (1997)      7.844000     9.0   Season 9 (1997)

In [10]:
alt.Chart(df_ratings).mark_line(point=True).encode(
    x=alt.X('season_label:O', title='Year', sort=alt.SortField(field='season', order='ascending')),
    y=alt.Y('imdb_rating:Q', title='Rating', scale=alt.Scale(domain=[6, 9]))
)

alt.Chart(...)

In [11]:
df_ratings = df_episodes[['season_label', 'imdb_rating', 'season', 'number_in_season']]
alt.Chart(df_ratings).mark_rect().encode(
    x=alt.X('number_in_season:O', title='Episode Number'),
    y=alt.Y('season_label:O', title='Season', sort=alt.SortField(field='season', order='ascending')),
    color=alt.Color('imdb_rating:Q', scale=alt.Scale(scheme='goldgreen'), title='IMDb Rating'),
    tooltip=['imdb_rating']
).properties(
    title='The Simpsons IMDb Ratings Heatmap',
    width=600,
    height=400
).configure_axis(
    labelFontSize=12,
    titleFontSize=14
)

alt.Chart(...)

## Question 2

In [12]:
df_viewers = df_episodes[['original_air_year', 'us_viewers_in_millions', 'season']]
df_viewers = df_viewers.groupby('season').agg({'us_viewers_in_millions': 'mean', 'original_air_year': 'median'})
df_viewers['original_air_year'] = round(df_viewers['original_air_year'] + 0.1)

In [13]:
alt.Chart(df_viewers).mark_line(point=True).encode(
    x=alt.X('original_air_year:O', title='Year'),
    y=alt.Y('us_viewers_in_millions:Q', title='Viewers in millions')
)

alt.Chart(...)

In [14]:
df_viewers = df_episodes[['original_air_year', 'us_viewers_in_millions', 'season']]
df_viewers = df_viewers.groupby('original_air_year').agg({'us_viewers_in_millions': 'mean', 'original_air_year': 'median'})
alt.Chart(df_viewers).mark_line(point=True).encode(
    x=alt.X('original_air_year:O', title='Year'),
    y=alt.Y('us_viewers_in_millions:Q', title='Viewers in millions')
)

alt.Chart(...)

In [43]:
df_viewers = df_episodes[['original_air_date', 'us_viewers_in_millions']]
df_viewers['date'] = pd.to_datetime(df_viewers['original_air_date'])
alt.Chart(df_viewers).mark_line(point=True).encode(
    x=alt.X('date:T', title='Date'),
    y=alt.Y('us_viewers_in_millions:Q', title='Viewers in millions')
)

C:\Users\20203666\AppData\Local\Temp\ipykernel_32168\1218155449.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_viewers['date'] = pd.to_datetime(df_viewers['original_air_date'])

alt.Chart(...)

In [67]:
# 1. Prepare the data
df_viewers = df_episodes[['original_air_date', 'us_viewers_in_millions']].copy()
df_viewers['date'] = pd.to_datetime(df_viewers['original_air_date'])


scatter = alt.Chart(df_viewers).mark_circle(opacity=0.5, size=40, color='steelblue').encode(
    x=alt.X('date:T', title='Air Date'),
    y=alt.Y('us_viewers_in_millions:Q', title='Viewers (Millions)')
)


line = alt.Chart(df_viewers).mark_line(color='red', size=2, point=False).encode(
    x='year(date):T',
    y='mean(us_viewers_in_millions):Q'
)
chart = scatter + line
chart

alt.LayerChart(...)

## Question 3

In [16]:
df_corr = df_episodes[['imdb_rating', 'us_viewers_in_millions']]

In [29]:
scatter = alt.Chart(df_corr, title='Correlation Between Viewers and Gradings').mark_circle(opacity=0.5).encode(
    x=alt.X('us_viewers_in_millions', title='Viewers (Millions)', scale=alt.Scale(zero=False)),
    y=alt.Y('imdb_rating', title='Grading (1-10)', scale=alt.Scale(zero=False))
)

In [31]:
chart = scatter + scatter.transform_regression('us_viewers_in_millions', 'imdb_rating').mark_line(color='red')
chart

alt.LayerChart(...)

## Question 4

In [32]:
df_episodes[['original_air_date']]

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views,season_label
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0,Season 1 (1989)
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0,Season 1 (1989)
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0,Season 2 (1990)
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0,Season 2 (1990)
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0,Season 2 (1990)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0,Season 23 (2011)
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0,Season 23 (2011)
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0,Season 24 (2012)
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0,Season 25 (2013)
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0,Season 25 (2013)

In [33]:
df_episodes['day'] = pd.to_datetime(df_episodes['original_air_date']).dt.day_name()
df_episodes

C:\Users\20203666\AppData\Local\Temp\ipykernel_32168\2532662728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_episodes['day'] = pd.to_datetime(df_episodes['original_air_date']).dt.day_name()

,id,image_url,imdb_rating,imdb_votes,number_in_season,number_in_series,original_air_date,original_air_year,production_code,season,title,us_viewers_in_millions,video_url,views,season_label,day
0,10,http://static-media.fxx.com/img/FX_Networks_-_...,7.4,1511.0,10,10,1990-03-25,1990,7G10,1,Homer's Night Out,30.30,http://www.simpsonsworld.com/video/275197507879,50816.0,Season 1 (1989),Sunday
1,12,http://static-media.fxx.com/img/FX_Networks_-_...,8.3,1716.0,12,12,1990-04-29,1990,7G12,1,Krusty Gets Busted,30.40,http://www.simpsonsworld.com/video/288019523914,62561.0,Season 1 (1989),Sunday
2,14,http://static-media.fxx.com/img/FX_Networks_-_...,8.2,1638.0,1,14,1990-10-11,1990,7F03,2,"Bart Gets an ""F""",33.60,http://www.simpsonsworld.com/video/260539459671,59575.0,Season 2 (1990),Thursday
3,17,http://static-media.fxx.com/img/FX_Networks_-_...,8.1,1457.0,4,17,1990-11-01,1990,7F01,2,Two Cars in Every Garage and Three Eyes on Eve...,26.10,http://www.simpsonsworld.com/video/260537411822,64959.0,Season 2 (1990),Thursday
4,19,http://static-media.fxx.com/img/FX_Networks_-_...,8.0,1366.0,6,19,1990-11-15,1990,7F08,2,Dead Putting Society,25.40,http://www.simpsonsworld.com/video/260539459670,50691.0,Season 2 (1990),Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,500,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,580.0,14,500,2012-02-19,2012,PABF07,23,At Long Last Leave,5.77,http://www.simpsonsworld.com/video/230541891832,45226.0,Season 23 (2011),Sunday
596,502,http://static-media.fxx.com/img/FX_Networks_-_...,7.3,541.0,16,502,2012-03-11,2012,PABF08,23,How I Wet Your Mother,4.97,http://www.simpsonsworld.com/video/230597187582,44818.0,Season 23 (2011),Sunday
597,511,http://static-media.fxx.com/img/FX_Networks_-_...,6.9,460.0,3,511,2012-11-04,2012,PABF18,24,Adventures in Baby-Getting,5.65,http://www.simpsonsworld.com/video/221688899646,39687.0,Season 24 (2012),Sunday
598,542,http://static-media.fxx.com/img/FX_Networks_-_...,6.4,473.0,12,542,2014-03-09,2014,SABF08,25,Diggs,2.69,http://www.simpsonsworld.com/video/310529091639,39292.0,Season 25 (2013),Sunday
599,548,http://static-media.fxx.com/img/FX_Networks_-_...,7.0,504.0,18,548,2014-04-13,2014,SABF13,25,Days of Future Future,3.64,http://www.simpsonsworld.com/video/310257731892,55742.0,Season 25 (2013),Sunday